### ISSUE TITLE
PolyGnome Upgrade : Feedback Consolidation

### ISSUE THREAD

**Issue by baconpaul** [baconpaul/BaconPlugs#72]
A bunch of issues on this module. Here's the consolidation of them

- [x] A Start/Stop button, a Run CV control and a Reset, both as input and output (#41)
- [x] Swap the Div/Mult display. The display should be "One pulse for every 2 underlies" and now it is backwards. (#54).
- [x] Clock CV is probably wrong. COmpare/Fix with CLOCKED and stuff. #56 
- [x] Label all the inputs and outputs #57
- [x] Label all the params
- [x] Add a PulseWidth option for each gate #57 
- [x] CLK CV in also #57
